const slides=[...document.querySelectorAll('.slide')];
let current=0;
const counter=document.querySelector('#counter');
slides.forEach((s,i)=>{s.id=`slide-${i+1}`;s.setAttribute('aria-label',`${i+1} of ${slides.length}: ${s.dataset.title}`);const f=document.createElement('div');f.className='slide-foot';f.innerHTML=`<span>Project Default / Jay Han</span><span class="folio">${String(i+1).padStart(2,'0')} / ${slides.length}</span>`;s.append(f);const b=document.createElement('button');b.className='nav-dot';b.setAttribute('aria-label',`Slide ${i+1}: ${s.dataset.title}`);b.onclick=()=>show(i);document.querySelector('#dots').append(b);});
function resize(){const full=!!document.fullscreenElement||document.body.classList.contains('theater');const overview=document.body.classList.contains('overview');const scale=Math.min((innerWidth- (full?0:48))/1440,overview?1:(innerHeight-(full?0:150))/810);document.documentElement.style.setProperty('--scale',Math.max(.1,scale));}
function show(i){current=Math.max(0,Math.min(slides.length-1,i));slides.forEach((s,n)=>{s.classList.toggle('active',n===current);s.setAttribute('aria-hidden',String(n!==current&&!document.body.classList.contains('overview')))});document.querySelectorAll('.nav-dot').forEach((b,n)=>{if(n===current)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});counter.textContent=`${current+1} / ${slides.length}`;document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;history.replaceState(null,'',`#${current+1}`);document.title=`${current+1}. ${slides[current].dataset.title} — Project Default`;}
function overview(){document.body.classList.toggle('overview');document.querySelector('#overview').setAttribute('aria-pressed',String(document.body.classList.contains('overview')));show(current);resize();}
async function present(){if(document.body.classList.contains('overview'))overview();if(document.fullscreenElement)await document.exitFullscreen();else if(document.body.classList.contains('theater'))document.body.classList.remove('theater');else{try{await document.documentElement.requestFullscreen()}catch{document.body.classList.add('theater')}}resize();}
function move(n){show(n);if(innerWidth<=1000)window.scrollTo(0,0);}
document.querySelector('#prev').onclick=()=>move(current-1);document.querySelector('#next').onclick=()=>move(current+1);document.querySelector('#overview').onclick=overview;document.querySelector('#fullscreen').onclick=present;document.querySelector('#print').onclick=()=>window.print();
addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;switch(e.key){case'ArrowRight':case'PageDown':move(current+1);break;case' ':if(e.target.closest('button,a'))return;move(current+1);break;case'ArrowLeft':case'PageUp':move(current-1);break;case'Home':move(0);break;case'End':move(slides.length-1);break;case'o':overview();break;case'f':present();break;case'Escape':document.body.classList.remove('theater');if(document.body.classList.contains('overview'))overview();resize();break;default:return}e.preventDefault()});
slides.forEach((s,i)=>s.addEventListener('click',e=>{if(document.body.classList.contains('overview')&&!e.target.closest('a')){overview();move(i)}}));
addEventListener('resize',resize);addEventListener('fullscreenchange',resize);addEventListener('hashchange',()=>show((parseInt(location.hash.slice(1))||1)-1));show((parseInt(location.hash.slice(1))||1)-1);resize();
